
/// Represents a range in the source code (byte offsets).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Span {
    pub start: usize,
    pub end: usize,
}

/// A Token paired with its location in the source code.
#[derive(Debug, Clone, PartialEq)]
pub struct SpannedToken {
    pub token: Token,
    pub span: Span,
}

/// Represents all possible lexical tokens generated by the lexer.
/// 
/// Note: `()` (parentheses) are intentionally not allowed in the general shell 
/// language and do not have tokens outside of specific evaluation contexts (like `${ }`).
#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    // general
    Word(String),
    Str(Vec<StrIntr>),
    Num(i64),
    Float(f64),
    
    // symbols
    NewLine,
    Eval,
    
    // punctuation
    SemiCln,
    Comma,
    And,
    
    // logical operators
    AndAnd,
    OrOr,
    Bang,
    
    // comparison & assign operators
    Assign,
    EqEq,
    NotEq,
    
    // shell operators
    Pipe,
    RdrctIn,
    RdrctOut,
    Append,
    
    // brackets
    LBrc,
    RBrc,
    LSqr,
    RSqr,
    
    // lang keywords
    Let,
    Print,
    If,
    Elif,
    Else,
    For,
    While,
    In,
    To,
    Break,
    True,
    False,
    
    // math operators
    Plus,
    Minus,
    Multiply,
    Divide,
    Modulo,
    Power,
    LPths,
    RPths,
    
    // end of file
    EOF,
}

/// Represents a segment of an interpolated string (either plain text or a variable).
#[derive(Debug, Clone, PartialEq)]
pub enum StrIntr {
    Literal(String),
    Variable(String),
}
